[[plugins]]
  repo = 'itchyny/lightline.vim'

[[plugins]]
  repo = 'prabirshrestha/async.vim'

[[plugins]]
  repo = 'prabirshrestha/vim-lsp'

[[plugins]]
  repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
  repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
  repo = 'ryanolsonx/vim-lsp-python'

[[plugins]]
  repo = 'joshdick/onedark.vim'

[[plugins]]
  repo = 'altercation/vim-colors-solarized'

[[plugins]]
  repo = 'tomasr/molokai'

[[plugins]]
  repo = 'cocopon/iceberg.vim'

[[plugins]]
  repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
  repo = 'airblade/vim-gitgutter'
